[package]
name = "bluestack"
version = "0.1.0"
edition = "2021"

[lints.rust.unexpected_cfgs]
level = "allow"
check-cfg = [
    'cfg(target_os, values("solana"))',
]

[lib]
crate-type = ["cdylib", "lib"]
doctest = false

[features]
alloc = []
client = []
debug = []
default = ["alloc"]

[dependencies]
quasar-lang = { git = "https://github.com/blueshift-gg/quasar" }
solana-instruction = { version = "3.2.0" }
